### ISSUE TITLE
words should be lowercase

### ISSUE THREAD

**Issue by fcbr** [own-pt/freeling_pt#1]
Keeping this here, so we don't loose track.  From Padro:

_Any word in the dictionary should be lowercased, since any word in the text is lowercased before being looked up. So, those are errors in current pt dictionary. They should be lowercased._

**Comment by livyreal** [comment]
@fcbr tem como vc fazer uma busca nos arquivos do dicionário para ver se tem outras entradas em upper case (além das dos nomes dos meses que já estão corrigidos)?
