### ISSUE TITLE
odd lemmas

### ISSUE THREAD

**Issue by livyreal** [own-pt/freeling_pt#12]
FL dic has the following entries:

> ótima bom AQ0FS0
> ótimas bom AQ0FP0
> ótimo bom AQ0MS0
> ótimos bom AQ0MP0

I strongly disagree that "ótimo" is a form of "bom". The tradicional grammar says that, but this does not hold in the real use of language and we will have WSD problems in latter modules of FL pipeline, since "ótimo" and "bom" are in different synsets of OWN-PT.

What do you think? Can I change the previous lemmatization of Garcia and Gamalo?

**Comment by arademaker** [comment]
I agree with you. This is wrong!! Actually, I believe that Garcia and Gamalo reported these problems in one of their papers.

**Comment by livyreal** [comment]
I didn't notice this report, but ok. I will fix them as

> ótimo ótimo AQ0MS0

**Comment by vcvpaiva** [comment]
I do not agree. I think this is useful information (about superlatives) that you are throwing away. but I do not know enough about the dictionary to make a strong point.

**Comment by livyreal** [comment]
@vcvpaiva we have in OWN-PT different synsets for "ótimo" and "bom". If we lemmatize all "ótimo" as "bom", the synset for those words would be wrongly selected. And more than that, I don't believe "ótimo" is the superlative of "bom" anymore, this is old traditional grammar.

**Comment by arademaker** [comment]
@vcvpaiva não entendeu eu acho. Nossa proposta é exatamente não trocar ótimo por bom e perder a informação do superlativo.

**Comment by vcvpaiva** [comment]
hmm entendi sim e acho que assim vamos perder a conexao entre bom e otimo, que eu acho que 'e boa, nao so' gramatica tradicional nao. mas enfim.

**Comment by livyreal** [comment]
digamos que a gente quisesse a conexão entre bom e ótimo, o fato de estar assim no dicionário não nos dá está conexão não e também não nos dá a informação de superlativo... ela tem de vir através do recurso lexical.

**Comment by arademaker** [comment]
Bem, se @vcvpaiva entendeu então @livyreal me parece que o argumento de @vcvpaiva deve ser de que se 'ótimo' é lematizado para 'bom' a conexão não é perdida porque sempre teremos a /word form/ original além do lema e POS tags para as etapas seguintes de processamento. Isto é temos a tripla ```(/word form/, lema, tag)``` que podem ser usadas nas etapas seguintes. Neste caso, pelo menos com FreeLing, o modulo de WSD irá usar apenas o lema para buscar o sense na OWN-PT, dai a conexão de ótimo para bom que @vcvpaiva  está comentando. Estou certo @vcvpaiva ?

Mas se ótimo e bom tiverem lemas diferentes, então apenas a OWN-PT poderá conectar as coisas, o que acho melhor.

Sobre bom, ótimo e melhor na OWN-PT:
http://wnpt.brlcloud.com/wn/synset?id=01123148-a (conexão direta com melhor)
http://wnpt.brlcloud.com/wn/synset?id=00227507-a (similar to http://wnpt.brlcloud.com/wn/synset?id=00228645-a)

Mas, POR FAVOR, não discutam neste issue as questões da OWN-PT.
