### ISSUE TITLE
wrong tokenization

### ISSUE THREAD

**Issue by livyreal** [own-pt/freeling_pt#14]
Some words in Fabricio report (simple_unknown) were actually wrongly tokenized.

They are:

crever
petáculo
tava
tar

It is possible to see it considering the generated sentences:

Longe_de os ensaios de o bumba-meu-boi , personalidades de a cultura , assim_como Chico_Saldanha , encontraram em o bumba-boi a inspiração para **' crever** livros , pintar quadros , compor músicas e criar ' petáculos teatrais . {crever}

What should we do?

**Comment by arademaker** [comment]
@livyreal do que estamos falando? São das frases produzidas ou da lista de palavras? Se crever deveria ser escrever, acho que basta vc verificar se no dict temos escrever. Se tivermos, ok. Se estamos falando das frases geradas então realmente talvez @fcbr tenha que examinar o que pode ter ocorrido.

**Comment by fcbr** [comment]
Esta frase veio do Amazonia.  As palavras estao escritas assim mesmo:

```Longe dos ensaios do bumba-meu-boi, personalidades da cultura, 
assim como Chico Saldanha, encontraram no bumba-boi a inspiração
para 'crever livros, pintar quadros, compor músicas e criar 'petáculos
teatrais.```

O que e', BTW, bastante curioso. Porque teoricamente o texto **original** no Overmundo esta' correto: http://www.overmundo.com.br/overblog/boi-como-inspiracao

**Comment by fcbr** [comment]
Humm, curiosamente apesar das frases estarem com coisas como `'crever`, a decomposicao delas nao!  Notem `'crever` no texto, mas `escrever` na decomposicao logo em seguida:

```

<s id=4565-1 texto="Blogs servem pra 'crever, certo?">
Blogs    [Blogs] <hum> PROP M/F S @SUBJ> #1->2
servem   [servir] <fmc> <mv> V PR 3P IND VFIN @FS-QUE #2->0
pra      [pra] PRP @<PIV #3->2
escrever         [escrever] <icl-fin> <mv> V INF @ICL-P< #4->3
$,  #5->0
certo    [certo] ADJ M S @<PRED #6->4
$?  #7->0
</s>
```

Para o processamento do FL nos extraimos os conteudo dos atributos `texto`.

**Comment by fcbr** [comment]
Parece que o processamento do Amazonia identificou e corrigiu estes coloquialismos (nunca vi ninguem escrever `'crever`, BTW, mas...).  Outro exemplo:

```
<s id=4565-19 texto="Ele começou a publicar na internet em 1996
 (sim, a data 'tá certa) a convite de um provedor que não existe mais.">
...
a        [o] <artd> DET F S @>N #13->14
data     [data] <np-def> <temp> N F S @SUBJ> #14->15
está     [estar] <cjt> <fmc> <mv> V PR 3S IND VFIN @FS-STA #15->2
certa    [certo] ADJ F S @<SC #16->15
...
```

Vejam que aqui eles corrigiram `'tá` para `está`.

Enfim, como nao estamos preocupados com estas construcoes informais agora (imagino), podemos ignorar estas palavras.  O que acham?

**Comment by livyreal** [comment]
o que eu achei estranho é que todas as palavras que vieram "cortadas" começam com es-. Por isto eu queria entender o que aconteceu com elas, mas ok. Vou simplesmente ignorar estas palavras.
