### ISSUE TITLE
contractions no dicionário

### ISSUE THREAD

**Issue by livyreal** [own-pt/freeling_pt#16]
entendendo as (PoS) tags e a relação do Freeling com Eagles

AR: SP é preposição mas o resto da tag "S00" não entendi! Vide página 67 deste artigo. Sobre como o simbolo + na tag http://nlp.lsi.upc.edu/freeling/doc/userman/html/node33.html
@Livy, temos que entender o que o segundo 'S' quer dizer para saber se estas entradas estão certas.

**Comment by livyreal** [comment]
Eagles para PREPOSIÇÕES:

<CENTER>
	<TABLE WIDTH=377 BORDER=1 CELLPADDING=2 CELLSPACING=2>
		<TR>
			<TH COLSPAN=4 VALIGN=TOP BGCOLOR="#ffffff">
				<P ALIGN=CENTER>PREPOSICIONES</P>
			</TH>
		</TR>
		<TR VALIGN=TOP>
			<TH WIDTH=12%>
				<P ALIGN=CENTER>Pos.</P>
			</TH>
			<TH WIDTH=37%>
				<P ALIGN=CENTER>Atributo</P>
			</TH>
			<TH WIDTH=32%>
				<P ALIGN=CENTER>Valor</P>
			</TH>
			<TH WIDTH=19%>
				<P ALIGN=CENTER>Código</P>
			</TH>
		</TR>
		<TR VALIGN=TOP>
			<TD WIDTH=12%><P ALIGN=CENTER>1</P></TD>
			<TD WIDTH=37%><P ALIGN=CENTER>Categoría</P></TD>
			<TD WIDTH=32%><P ALIGN=CENTER>Adposición</P></TD>
			<TD WIDTH=19%><P ALIGN=CENTER>S</P></TD>
		</TR>
		<TR VALIGN=TOP>
			<TD WIDTH=12%><P ALIGN=CENTER>2</P></TD>
			<TD WIDTH=37%><P ALIGN=CENTER>Tipo</P></TD>
			<TD WIDTH=32%><P ALIGN=CENTER>Preposición</P></TD>
			<TD WIDTH=19%><P ALIGN=CENTER>P</P></TD>
		</TR>
		<TR VALIGN=TOP>
			<TD ROWSPAN=2 WIDTH=12%><P ALIGN=CENTER>3</P></TD>
			<TD ROWSPAN=2 WIDTH=37%><P ALIGN=CENTER>Forma</P></TD>
			<TD WIDTH=32%><P ALIGN=CENTER>Simple</P></TD>
			<TD WIDTH=19%><P ALIGN=CENTER>S</P></TD>
		</TR>
		<TR VALIGN=TOP>
			<TD WIDTH=32%><P ALIGN=CENTER>Contraída</P></TD>
			<TD WIDTH=19%><P ALIGN=CENTER>C</P></TD>
		</TR>
		<TR VALIGN=TOP>
			<TD WIDTH=12%><P ALIGN=CENTER>3</P></TD>
			<TD WIDTH=37%><P ALIGN=CENTER>Género</P></TD>
			<TD WIDTH=32%><P ALIGN=CENTER>Masculino</P></TD>
			<TD WIDTH=19%><P ALIGN=CENTER>M</P></TD>
		</TR>
		<TR VALIGN=TOP>
			<TD WIDTH=12%><P ALIGN=CENTER>4</P></TD>
			<TD WIDTH=37%><P ALIGN=CENTER>Número</P></TD>
			<TD WIDTH=32%><P ALIGN=CENTER>Singular</P></TD>
			<TD WIDTH=19%><P ALIGN=CENTER>S</P></TD>
		</TR>
	</TABLE>
</CENTER>



[http://nlp.lsi.upc.edu/freeling/doc/tagsets/tagset-es.html#preposiciones](url)

**Comment by arademaker** [comment]
@livyreal acho que vc não leu minha mensagem original que possivelmente originou este seus comentários. Estou copiando aqui o que escrevi naquela mensagem:



Aproveitando nossa discussão e ligando ela ao trabalho que estamos fazendo de ir melhorando o suporte PT de Freeling, resolvi dar uma olhad no dicionário Freeling dado que só tem "pelos" mas não "pelo":

No arquivo https://github.com/own-pt/freeling_pt/blob/master/dictionary/entries/other:

pelos por+os SPS00+*

E estou colocando:

pelo por+o SPS00+*

Lendo: M. Garcia and P. Gamallo, “Análise Morfossintáctica para Português Europeu e Galego: Problemas, Soluções e Avaliação,” pp. 1–9, May 2010.

SP é preposição mas o resto da tag "S00" não entendi! Vide página 67 deste artigo. Sobre como o simbolo + na tag http://nlp.lsi.upc.edu/freeling/doc/userman/html/node33.html

@livyreal , temos que entender o que o segundo 'S' quer dizer para saber se estas entradas estão certas. Pelo doc do FreeLing, "pelo" vira por+o onde "por" fica com tag SPS00 e "o" recebe todas as possiveis análises que depois a melhor será escolhida (modelo estatístico):

```
root@26378cd0ba62:/# echo "Pelo teor da nova lei." | analyze -f /usr/local/share/freeling/config/pt.cfg
Por por SPS00 1
o o DA0MS0 1
teor teor NCMS000 1
de de SPS00 1
a o DA0FS0 0.676943 a SPS00 0.311806 o PP3FSA00 0.00614912 o PD0FS000 0.00498492 a NCMS000 0.000116421
nova novo AQ0FS0 0.998489
lei lei NCFS000 1
. . Fp 1
```

Por que "por" só ocorre com SPS00 no dicionário:

```
urca:entries arademaker$ egrep -i "^por " *
other:por por SPS00
```

E porque dentre as opções de entradas para "o" ele escolheu a entrada com tag DA0MS0 (determinante artigo):

```
urca:entries arademaker$ egrep -i "^o " *
nouns:o o NCMS000
other:o o DA0MS0
other:o o PD0MS000
other:o o PP3MSA00
```


Chalub respondeu:

"Eu extrai a tabela 4 e converti para texto, vide anexo.  Em particular veja que as preposicoes so' admitem o valor "SPS" (aposicao-preposicao-simples).  Me parece que 00 e' so um "filler".

Nos nossos experimentos internos aqui com varios corpora, so' encontrei este valor para preposicoes: SPS00."

E completou:

"BTW: o Parole, tag set o qual eles dizem ter sido usado como base, contem outras variantes de tags para preposicoes: http://www.cs.upc.edu/~nlp/tools/parole-eng.html

Em particular, na mudanca do "Parole" para o "Estreito", nos ficamos apenas com preposicoes simples, mas la' podem existir preposicoes "contracted".

Os ultimos dois valores eram sempre "masculine" e "singular" que foram convertidos apenas para 0 nesta versao nova, pelo visto."

E eu respondi:

"Parole? Estreito? Depois precisamos entender a relação destes com EAGLES! De qq modo, entendi que a mudança que fiz no dicionário está correta então."

**Comment by arademaker** [comment]
@fcbr vc acha que ficou algo pendente em relação a isso?

**Comment by fcbr** [comment]
nao

**Comment by arademaker** [comment]
De Luiza:

Em anexo, envio a lista que fiz com as "descontrações" do MacMorpho e as contrações equivalentes. Exemplificando com a primeira linha: 

```
De_PREP entre_PREP --- Dentre_PREP
```

Isso significa que no MM ela aparece como De_PREP entre_PREP, e no padrão UD deveria aparecer como

```
1-2 Dentre
1 De
2 entre
```

Não sabia se você precisaria das etiquetas, mas, por via das dúvidas, achei melhor botar. 

@livyreal podemos usar a lista anexa para confererir a cobertura do dicc. Os dados vieram do Mac Morpho.

[Contracoes.txt](https://github.com/own-pt/freeling_pt/files/199589/Contracoes.txt)

**Comment by arademaker** [comment]
```
; SLIME 2016-02-10
cl-user> (ql:quickload :fare-csv)
To load "fare-csv":
  Load 1 ASDF system:
    fare-csv
; Loading "fare-csv"

cl-user> (mapcar (lambda (a) (string-downcase (car a)))
		 (fare-csv:read-csv-file "/Users/arademaker/Downloads/contracoes.txt"))
("dentre" "dentre" "pelo" "pela" "pelos" "pelas" "pelo" "pela" "pelos"
 "pelas" "ao" "aos" "ao" "aos" "no" "na" "nos" "nas" "no" "na" "nos"
 "nas" "nesse" "nessa" "nesses" "nessas" "nesse" "nessa" "nesses"
 "nessas" "neste" "nesta" "nestes" "nestas" "neste" "nesta" "nestes"
 "nestas" "naquele" "naquela" "naqueles" "naquelas" "naquele" "naquela"
 "naqueles" "naquelas" "nisto" "nisso" "nisto" "nisso" "naquilo"
 "naquilo" "nele" "nela" "neles" "nelas" "nele" "nela" "neles" "nelas"
 "no" "na" "nos" "nas" "no" "na" "nos" "nas" "daqui" "daqui" "daí"
 "daí" "dali" "dali" "dele" "dela" "deles" "delas" "dele" "dela"
 "deles" "delas" "do" "da" "dos" "das" "do" "da" "dos" "das" "desse"
 "dessa" "desses" "dessas" "desse" "dessa" "desses" "dessas" "deste"
 "desta" "destes" "destas" "deste" "desta" "destes" "destas" "daquele"
 "daquela" "daqueles" "daquelas" "daquele" "daquela" "daqueles"
 "daquelas" "disto" "disso" "disto" "disso" "daquilo" "daquilo" "à"
 "às" "à" "às")
cl-user> (mapcar #'car
		 (fare-csv:read-csv-file "../work/freeling-3.1/data/pt/dictionary/entries/other"))
("à" "a" "a" "a" "a" "aí" "abafa" "abaixo" "aboca" "abracadabra"
 "abrenúncio" "acerca" "acima" "adei" "adeus" "adiante" "afasta"
 "afora" "ah" "ai" "ailó" "alô" "ala" "aleluia" "alerta" "alevá" "algo"
 "algum" "algum" "alguém" "alguma" "alguma" "algumas" "algumas"
 "alguns" "alguns" "alivia" "alto" "ambas" "ambas" "ambos" "ambos"
 "amen" "amém" "amén" "ante" "ao" "aos" "apenas" "apesar" "após"
 "aquando" "aquela" "aquela" "aquelas" "aquelas" "aquele" "aquele"
 "aqueles" "aqueles" "aqueloutra" "aqueloutras" "aqueloutro"
 "aqueloutros" "aquilo" "arre" "arreda" "arrenego" "arriba" "as" "as"
 "as" "assim" "asta" ...)
cl-user> (set-difference ** * :test #'string=)
("disto" "disto" "destes" "deste" "destes" "deste" "dessas" "desses"
 "dessa" "desse" "dessas" "desses" "dessa" "desse" "pelas" "pela"
 "pelas" "pela")
cl-user> 
```

A ultima relação é que importa, lista das contrações que ainda não estão no dicionário! 

```
("disto" "disto" "destes" "deste" "destes" "deste" "dessas" "desses"
 "dessa" "desse" "dessas" "desses" "dessa" "desse" "pelas" "pela"
 "pelas" "pela")
```

**Comment by livyreal** [comment]
added no último commit
> disto, destes, deste, dessas, desses, dessa, desse, pelas, pela
