### ISSUE TITLE
numerals

### ISSUE THREAD

**Issue by livyreal** [own-pt/freeling_pt#4]
What should we do with numerals?
The only two we have ("um" e "dous") are in the noun file tagged as noun. Already asked an advice to Padró.

**Comment by vcvpaiva** [comment]
What do you mean the only two we have? where? the the Bosque corpus there are plenty.

**Comment by arademaker** [comment]
Livy is talking about the freeling dictionary, right?

**Comment by livyreal** [comment]
Padró on dates and numbers (Feb, 19 - Feb, 26)

    Yes, the dates detection module should detect several date patterns.

    From basic DD/MM/AAAA, to more complex such as "prima feria, 23 de Novembro de 1993", and many others.

    The problem is that this module is hardcoded in the program, and can not be configured.
    If it does not work properly, please let me know in which cases does it fail and I can take a look.

[...]
   The dates module does not use the dictionary.

   So, having months in the dictionary is only useful in case you deactivate the dates module and want to get an analysis that does not come from the guesser

[...]
The dates module requires that numbers have been marked as such, which 
is done by the numbers module.
[...]
LR:
> I would like to add numerals in the dictionary, but I would like your 
> advise about in which file they should be. Considering we have files 
> for nouns, adj, adv, verb and other, I would add them on "adj" as 
> numerals work as adjectives. However "um" and "dois" are already in 
> the noun file with the tag common nouns (um um NCMS000). What do you 
> think? Should I keep this "nominal" view on numerals?
>
LLP:
     You can, if you want to consider cases such as  "o dois es o meu 
numero preferido"
     Anyway, since the frequency of these cases will be very low, the 
tagger will probably learn to tag them always as number.

[...]
FreeLing uses "Z" for numerals, though some languages (e.g. 
Spanish) use also AOxxxxx for ordinal adjectives.
    Ordinal adjectives should be in the dictionary.
    Cardinal numbers don't have to be if you use the numbers module.

LR: Even cardinals as "um", "dois, três"? The numbers module couldn't detect "três" or "3".

  Yes.
  Even more: cardinals as "três mil quatrozentos seis" should be also recognized.

**Comment by livyreal** [comment]
We already decide for not having in the dictionary numbers (ordinal and cardinal), as FL Number Module recognition seems to be able to correctly tag them as numbers (PoS: Z).
