### ISSUE TITLE
PB vs PE

### ISSUE THREAD

**Issue by livyreal** [own-pt/freeling_pt#5]
Consider the follow (from noun dictionary file):

projecto projecto NCMS000
projectos projecto NCMP000

To include in Freeling dictionary, BP words, in this case **projeto** e **projetos**, should I keep the lemma "projecto"? 

Thinking on OWN-PT: http://wnpt.brlcloud.com/wn/synset?id=05898568-n  we have "projecto" e "projeto" in the same synset, but it does not hold for other PE words, as diretor/director (we have a lot of synsets with only "diretor"), the same for other words (as atuação/ator).

A possible solution is to add BP words under the PE lemma (projeto projecto ---- diretor director) and then open an issue to complete those ways of spelling in OWN-PT.

**Comment by vcvpaiva** [comment]
Yes, it seems to me that the only thing to do is to add the European Portuguese spelling, if and when  we need it.

**Comment by arademaker** [comment]
Considerando a iniciativa da revisão ortográfica que tenta unificar os vários "portugueses", acho que devemos considerar, na medida do possível, que estamos produzindo um dicionário único para todas as variantes. Vale ler novamente trabalhos do Garcia e Gamalo que discutem, vide links abaixo.

Não acho razoável a sugestão de misturar conceitos de lematização com conversão de variantes, isto certamente deria problema. Acho que adicionamos entradas PB e PE (por demanda, ou apenas deixamos o que tiver) com seus respectivos lemas.

Obviamente, podemos ter problemas com isso, mas esta seria minha sugestão de estratégia básica. Não entendi sua conexão com a OWN-PT, obviamente, ter 1-1 das palavras do dicionário com a OWN-PT é um objetivo bem distante.

1. P. Gamallo and M. Garcia, “FreeLing e TreeTagger: um estudo comparativo no âmbito do Português,” gramatica.usc.es. [Online]. Available: http://gramatica.usc.es/~gamallo/artigos-web/PROLNAT_Report_01.pdf. [Accessed: 04-Sep-2015].
2. M. Garcia and P. Gamallo, “Using Morphosyntactic Post-processing to Improve POS-tagging Accuracy,” inf.pucrs.br. [Online]. Available: https://www.inf.pucrs.br/~propor2010/proceedings/regular_papers/GarciaGamallo.pdf. [Accessed: 01-Sep-2015].
3. M. Garcia, P. Gamallo, I. Gayo, and M. A. P. Cruz, “PoS-tagging the Web in Portuguese. National varieties, text typologies and spelling systems,” Procesamiento del Lenguaje Natural, vol. 53, no. 0, pp. 95–101, Sep. 2014.
4. M. Garcia and P. Gamallo, “Análise Morfossintáctica para Português Europeu e Galego: Problemas, Soluções e Avaliação,” pp. 1–9, May 2010.

**Comment by livyreal** [comment]
Alexandre, se eu adicionar "projeto projeto", vamos estar assumindo que **projeto** é diferente de **projecto**. Queremos isto?

**Comment by arademaker** [comment]
@livyreal não ! vc não vai estar assumindo nada, este não é um dicionário de senses, apenas de formas lexicais. E sim, queremos deixar explicito que são formas diferenes com seus respectivos lemas e inflexões.

**Comment by livyreal** [comment]
ok, vou fazer isto hj entao.

**Comment by arademaker** [comment]
@livyreal para facilitar seu trabalho, clonei o repo para nosso diretório no dropbox.  Trabalhe nos arquivos lá sem se preocupar com  o git. Me avise quando fizar mudanças e eu faço commit e push. Na primeira oportunidade te ajudo com o git.

**Comment by livyreal** [comment]
we already decided for keeping Brazilian spelling in the lemmatization (not only in entries), then:

> projeto projeto NCMS000
>atuação atuação NCFS000

We do not earn anything lemmatizing BP words in EP forms and many of our synsets do not have the EP spelling and maybe some task would need this PB/BP differences encoded in the lemmatization.
