### ISSUE TITLE
adj vs nouns

### ISSUE THREAD

**Issue by livyreal** [own-pt/freeling_pt#6]
em relação a palavras que aparecem na /simple-unknown.txt e podem ser adjetivos ou nomes (atores, petista, efetivo), add as duas ou considero apenas os casos das frases gerados pelo Chalub?

@fcbr o phrases-words-top-200.txt ainda nao tem as frases, certo?

**Comment by arademaker** [comment]
@livyreal acho que temos que considerar as duas, por isso cada forma pode ter mais de um lemma e tag de POS. Dos seus exemplos, atores tem o lema ator e tags possiveis de nome e adj.
