### ISSUE TITLE
what to do with abbreviations, underscores and hyphens?

### ISSUE THREAD

**Issue by vcvpaiva** [own-pt/freeling_pt#7]
There was a decision (on the real OWN-PT) to forsake underscores (which exist in PWN) for spaces.

But the writers of corpora and the processing techniques applied to these corpora 
sometimes use hyphens, some times spaces, sometimes underscore:
e.g. fim_de_semana, fim de semana, final de semana, ponto de vista, ponto_de_vista.

this causes "missing" items in the reports in http://wnpt.brlcloud.com/wn/prototypes/corpora

Similarly we have abbreviations that also cannot be found:  r. (23), nº (9), dr. (8)

**Comment by livyreal** [comment]
@vcvpaiva this is also a question on Freeling Dic, but the decisions may be different regarding to what to do in OWN-PT and in the dictionary. Don't you want to open this issue in OWN-PT repo and not here?

**Comment by arademaker** [comment]
Abreviações são tratadas por freeling pelo modulo tokenizer [1] então é este arquivo de configuração que precisamos /aprimorar/. 

https://github.com/own-pt/freeling_pt/blob/master/tokenizer.dat

Underscore é usado pelo freeling para juntar tokens em MWE e para os hífens temos que pesquisar se podemos controlar quando e como separar. Este issue está muito genérico. Vou fechar se se @vcvpaiva tiver uma demanda mais específica, peço reabrir explicando. 

[1] http://nlp.lsi.upc.edu/freeling/doc/userman/html/node22.html

**Comment by vcvpaiva** [comment]
Re-opening as we need to keep a list of abbreviations that will be added to OWN-PT: so far nº , dr. (8), 1º.

**Comment by arademaker** [comment]
@vcvpaiva no! We don't have to keep the list here, you can contribute editing the file mentioned above directly or @livyreal can.

**Comment by vcvpaiva** [comment]
@arademaker the point is to have a list maintained in common for the OWN-PT, not for the dictionary that  Livy is keeping, correct?
