### ISSUE TITLE
lemmas: adj vs lexicalized noun

### ISSUE THREAD

**Issue by livyreal** [own-pt/freeling_pt#9]
Some words that were already in Freeling dic seem to me wrongly lemmatized:

>directa directa NCMS000
>directas directa NCMP000
>directriz directriz NCFS000
>directrizes directriz NCFP000

(but: disciplinadoras disciplinador NCFP000
actrizes actor NCFP000)

first case, "directa" could be view as "levei uma direta e não esperei mais", ou "depois das diretas, a politica mudou". and then I don't know if "directo" as a lemma can capture it. But in "Eu prefiro a direta", the lemma "directo/direto" is enough.

The second case depends on how we understand this gender process. This formation is REGULAR, but it is not the most common.

It seems to be that the best would have "directo" and "diretor" as lemmas. What you think?

**Comment by livyreal** [comment]
Other interesting word:

>objetiva objetiva NCFS000
>objetivas objetiva NCFP000

If we think on the lens, "objetiva" should be the lemma, but if we think in the general pipeline, in "a objetiva estava muito difícil" (objetiva stading for "prova objetiva"), "objetiva must be tagged as a noun, I suppose. I will ask to Padró if adjectives alone can be subjects in the parser module.

**Comment by livyreal** [comment]
another interesting example (and easier than the others):

>coletiva 
> coletivo 

As adjectives, they have the same lemma (coletivo), as nouns, 'coletiva' is a big interview (coletiva de imprensa) and 'coletivo' is bus/group, then different lemmas in NOUN.file, but same lemma in adj.FILE.

**Comment by arademaker** [comment]
good to report here these "hard" cases. We will need to write about them at some moment.

**Comment by arademaker** [comment]
But keep in mind the issues must have a purpose. A issue is something to be done and closed. Please be clear about what do you have to do to close this issue.

**Comment by vcvpaiva** [comment]
Livy, I think in the dictionary it does not make much of a difference and we can add all these flexed versions that tend to mean different things.  there is no need to be parsimonious with the dictionary, it seems to me. 
it's a very different story when it comes to the OWN-PT. There I think we will need to add many "feminine" nouns that we had forgotten about (e.g. alta-de precos, secadora-de roupas) as for these the  ending is essential, but I don't think we need to add many of examples that you mention. 

it seems to me that "direta" from `Diretas Ja'' 'e um adjetivo, it really means "(eleicao) direta" in the phrase  "depois das diretas, a politica mudou". there is no noun "direta" that means "uma eleica direta".

**Comment by arademaker** [comment]
I don't really agree with @vcvpaiva in not being parsimonious with the dictionary! The dictionary quality impacts the POS tagger and all further modules of FreeLing. I agree with analysis but I believe we do need to understand well how to improve the dict and how to work with the afixos.

**Comment by vcvpaiva** [comment]
what's the example of where having too many words will cause problems @arademaker?

**Comment by livyreal** [comment]
I consider "coletiva", "objetiva" and "direta" already kind of lexicalized nouns. They, as nouns, already bring the compound meaning and are more often used as nouns.

My point is: if I don't have "objetiva objetiva" in the dic, in the sentence "Minha objetiva sujou de areia", "objetiva" will be tagged as "objetivo" and then, in the WSD module, a proper synset with the word "objetiva" will not be considered, if we don't change the FL pipeline.

**Comment by arademaker** [comment]
FL? I agree, if the word is not tagged as noun the WSD will fail to find in a proper synset.

**Comment by livyreal** [comment]
Freeling = FL

**Comment by arademaker** [comment]
yes

**Comment by vcvpaiva** [comment]
The three examples you mentioned are Named Entities: Diretas Ja', Canudos and Estado Novo are named entities, good writers would use capitals for them. if the dictionary has named entities, then by all means, add them in. IF the dictionary is only about common nouns, NO, don't add them.

**Comment by livyreal** [comment]
I know they are NE, but I'm thinking on OWN-PT (we do have several NEs and I'd like to have those historical Brazilian moments there,  PWN already has "revolução francesa" and many important wars to English speakers).

About NE in FL dic, there is no uniform treatment to NEs. We have "brasil" and "lisboa", but not "portugal". We have "maria" and "mariana", but they are tagged as NC (nome comum). FL has a tag for proper nouns (NP) but in PT dictionary there is NO proper nouns (or nouns tagged as NP). That is interesting...

**Comment by arademaker** [comment]
Please add an issue for discuss:
About NE in FL dic, there is no uniform treatment to NEs. We have "brasil" and "lisboa", but not "portugal". We have "maria" and "mariana", but they are tagged as NC (nome comum). FL has a tag for proper nouns (NP) but in PT dictionary there is NO proper nouns (or nouns tagged as NP). That is interesting...

I don't think they should be in the dict. We can ask Padro...

**Comment by vcvpaiva** [comment]
well,

> About NE in FL dic, there is no uniform treatment to NEs. We have "brasil" and "lisboa", but not "portugal". We have "maria" and "mariana", but they are tagged as NC (nome comum). FL has a tag for proper nouns (NP) but in PT dictionary there is NO proper nouns (or nouns tagged as NP).

this is wrong, simply. if the dictionary will not make a difference between proper and common nouns, life will be difficult, it seems to me.
